# -*- coding: utf-8 -*-
"""CS01-17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DlZs7yuaM8nhKP2n2GIjWTrnkEa7oJqq
"""

from numpy import random
x = random.randint(100, size=(5,10))
print(np.sort(x))